services:
  radarr4k:

    labels:
      traefik.docker.network: "proxy"
      traefik.enable: true
      traefik.http.middlewares.radarr4k-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.radarr4k-secure.entrypoints: "https"
      traefik.http.routers.radarr4k-secure.rule: "Host(`radarr4k.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.radarr4k-secure.service: "radarr4k"
      traefik.http.routers.radarr4k-secure.tls: true
      traefik.http.routers.radarr4k.entrypoints: "http"
      traefik.http.routers.radarr4k.middlewares: "radarr4k-https-redirect"
      traefik.http.routers.radarr4k.rule: "Host(`radarr4k.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.services.radarr4k.loadbalancer.server.port: 7878
