services:
  tautulli:
    labels:
      traefik.docker.network: "proxy"
      traefik.enable: true
      traefik.http.middlewares.tautulli-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.tautulli-secure.entrypoints: "https"
      traefik.http.routers.tautulli-secure.rule: "Host(`tautulli.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.tautulli-secure.service: "tautulli"
      traefik.http.routers.tautulli-secure.tls: true
      traefik.http.routers.tautulli.entrypoints: "http"
      traefik.http.routers.tautulli.middlewares: "tautulli-https-redirect"
      traefik.http.routers.tautulli.rule: "Host(`tautulli.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.services.tautulli.loadbalancer.server.port: 8181
