services:
  whisparr:
    image: ghcr.io/hotio/whisparr:latest
    container_name: whisparr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${MEDIA_PATH}:/media
