services:
  overseerr:
    labels:
      traefik.docker.network: "proxy"
      traefik.enable: true
      traefik.http.middlewares.overseerr-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.overseerr-secure.entrypoints: "https"
      traefik.http.routers.overseerr-secure.rule: "Host(`overseerr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.overseerr-secure.service: "overseerr"
      traefik.http.routers.overseerr-secure.tls: true
      traefik.http.routers.overseerr.entrypoints: "http"
      traefik.http.routers.overseerr.middlewares: "overseerr-https-redirect"
      traefik.http.routers.overseerr.rule: "Host(`overseerr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.services.overseerr.loadbalancer.server.port: 5055
