services:
  prowlarr:
    labels:
      traefik.docker.network: "proxy"
      traefik.enable: true
      traefik.http.middlewares.prowlarr-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.prowlarr-secure.entrypoints: "https"
      traefik.http.routers.prowlarr-secure.rule: "Host(`prowlarr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.prowlarr-secure.service: "prowlarr"
      traefik.http.routers.prowlarr-secure.tls: true
      traefik.http.routers.prowlarr.entrypoints: "http"
      traefik.http.routers.prowlarr.middlewares: "prowlarr-https-redirect"
      traefik.http.routers.prowlarr.rule: "Host(`prowlarr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
