services:
  traefik:
    environment:
      TRAEFIK_API_DASHBOARD: true
      TRAEFIK_API_DEBUG: true
      TRAEFIK_API: true
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: "https"
      TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_TO: "https"
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ":443"
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: "unix:///var/run/docker.sock"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_FILE_FILENAME: "/config.yml"
      TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY: true
