services:
  traefik:
    labels:
      traefik.enable: true
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.http.middlewares.traefik-auth.basicauth.users: "${ADMIN_CREDS}"
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.traefik-secure.entrypoints: "https"
      traefik.http.routers.traefik-secure.middlewares: "traefik-auth"
      traefik.http.routers.traefik-secure.rule: "Host(`traefik.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.traefik-secure.service: "api@internal"
      traefik.http.routers.traefik-secure.tls: true
      traefik.http.routers.traefik-secure.tls.certresolver: "digitalocean"
      traefik.http.routers.traefik-secure.tls.domains[0].main: "${SUBDOMAIN}.${DOMAIN}"
      traefik.http.routers.traefik-secure.tls.domains[0].sans: "*.${SUBDOMAIN}.${DOMAIN}"
      traefik.http.routers.traefik.entrypoints: "http"
      traefik.http.routers.traefik.middlewares: "traefik-https-redirect"
      traefik.http.routers.traefik.rule: "Host(`traefik.${SUBDOMAIN}.${DOMAIN}`)"
