services:
  radarr:
    labels:
      traefik.docker.network: "proxy"
      traefik.enable: true
      traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.radarr-secure.entrypoints: "https"
      traefik.http.routers.radarr-secure.rule: "Host(`radarr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.radarr-secure.service: "radarr"
      traefik.http.routers.radarr-secure.tls: true
      traefik.http.routers.radarr.entrypoints: "http"
      traefik.http.routers.radarr.middlewares: "radarr-https-redirect"
      traefik.http.routers.radarr.rule: "Host(`radarr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.services.radarr.loadbalancer.server.port: 7878
