services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}:/opt/adguardhome/conf
      - ${DATA_PATH}:/opt/adguardhome/work
