services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_PATH}:/var/jenkins_home
  jenkins-ssh-agent:
    image: jenkins/ssh-agent:latest
    container_name: jenkins-ssh-agent
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
