services:
  jenkins:
    labels:
      traefik.docker.network: "proxy"
      traefik.enable: true
      traefik.http.middlewares.jenkins-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.jenkins-secure.entrypoints: "https"
      traefik.http.routers.jenkins-secure.rule: "Host(`jenkins.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.jenkins-secure.service: "jenkins"
      traefik.http.routers.jenkins-secure.tls: true
      traefik.http.routers.jenkins.entrypoints: "http"
      traefik.http.routers.jenkins.middlewares: "jenkins-https-redirect"
      traefik.http.routers.jenkins.rule: "Host(`jenkins.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.services.jenkins.loadbalancer.server.port: 8080