services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: "--advertise-exit-node"
      TS_HOSTNAME: ${TS_HOSTNAME}
      TS_ROUTES: ${TS_ROUTES}
      TS_STATE_DIR: /var/lib/tailscale
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/net/tun:/dev/net/tun
      - ${DATA_PATH}:/var/lib
