services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${MEDIA_PATH}:/media
