services:
  maintainerr:
    image: jorenn92/maintainerr:latest
    container_name: maintainerr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_PATH}:/data
