services:
  maintainerr:
    labels:
      traefik.docker.network: "proxy"
      traefik.enable: true
      traefik.http.middlewares.maintainerr-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.maintainerr-secure.entrypoints: "https"
      traefik.http.routers.maintainerr-secure.rule: "Host(`maintainerr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.maintainerr-secure.service: "maintainerr"
      traefik.http.routers.maintainerr-secure.tls: true
      traefik.http.routers.maintainerr.entrypoints: "http"
      traefik.http.routers.maintainerr.middlewares: "maintainerr-https-redirect"
      traefik.http.routers.maintainerr.rule: "Host(`maintainerr.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.services.maintainerr.loadbalancer.server.port: 6246
